name: "\U0001F41E Bug Report"
description: Report a bug in Virtual Media Folders - Media Cleanup
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below so we can investigate and fix it as quickly as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise summary of what the bug is.
      placeholder: Describe the bug…
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      value: |
        1. Go to …
        2. Click on …
        3. Scroll down to …
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected…
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened…
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recordings
      description: If applicable, add screenshots or screen recordings to help explain the problem. You can drag and drop images here.
      placeholder: Drag and drop images or paste links here…
    validations:
      required: false

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which version of Media Cleanup are you running?
      placeholder: "1.1.1"
    validations:
      required: true

  - type: input
    id: wp-version
    attributes:
      label: WordPress Version
      description: Which version of WordPress are you running?
      placeholder: "6.8"
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Which version of PHP is your server running?
      placeholder: "8.3"
    validations:
      required: true

  - type: dropdown
    id: scan-type
    attributes:
      label: Scan Type
      description: Which scan or detection type is affected? (if applicable)
      options:
        - Unused media detection
        - Duplicate detection (SHA-256)
        - Oversized file detection
        - Background scanning (Action Scheduler)
        - Archive action
        - Trash action
        - Flag for review
        - WP-CLI command
        - Not applicable
    validations:
      required: false

  - type: input
    id: media-library-size
    attributes:
      label: Media Library Size
      description: Approximately how many media items are in your library? (helps us reproduce performance issues)
      placeholder: "e.g. 500, 5000, 50000"
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using? (if relevant)
      placeholder: "e.g. Chrome 120, Safari 17, Firefox 121"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem — e.g. other active plugins, theme, multisite, error log output.
      placeholder: Any other details that might help…
    validations:
      required: false
